### ISSUE TITLE
[Discussion] Better unit test framework

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#103]
Our current unit test system is based off reading in files and then comparing attributes and containers to hard-coded values. I have a few issues with this framework, while it has been the easiest to implement and get running.

1. Each test file is found by searching from the `ROOT` attribute found using `__file__` - [example: main `__init__.py`](https://github.com/CORE-GATECH-GROUP/serpent-tools/blob/develop/serpentTools/__init__.py#L3).
1. We still get a lot of WARNING/ERROR statements in our testing, even when that *should* happen - example: [build 163](https://travis-ci.org/CORE-GATECH-GROUP/serpent-tools/jobs/357795024#L1203)

## Use of `__file__`

When `__file__` is used, python will print out [warnings](https://travis-ci.org/CORE-GATECH-GROUP/serpent-tools/jobs/357795024#L680) stating something along the lines of

> `module references __file__`

I don't really like this, and I think this may be cause for concern at other institutions moving forward. I've also found some evidence that use a `__file__` may cause issues moving for building python distributions like wheels and eggs.

### Proposal
Convert test files into importable objects, maybe in a `serpentTools.data` directory, that replace the various text files that are stored with the project. This way, people can try and recreate our tests or examples wherever they are with something like `from serpentTools.data import bwr_det0` and the full test string (or a readable object) will be returned.

When we read from a file, the readers all call something like 
```
with open(self.filePath, 'r') as out:
    <do stuff>
````
If the object that is imported from `serpentTools.data.bwr_det0` has the necessary `__enter__`,`__exit__`, and read methods, then we should be able to directly read from these psuedo-files, something like [`StringIO`](https://docs.python.org/2/library/stringio.html)

## Excessive messages
When someone runs `python setup.py test` on our project, they will still see many error and warning messages as the code does what it does. These may give the impression that our tests and package are riddled with errors, even though the tests pass. 

### Proposal
We have the capabilities, through the `settings.rc` object to control the logger. If we simply set this logger level to `CRITICAL` or higher, then no messages should be raised. There may be even better ways to handle this, but I am not entirely sure at this point.

I welcome any thoughts on this matter to be posted here on this issue

**Comment by drewejohnson** [comment]
Did some digging today and I found that using `__file__` is moderately common in some popular python packages

* [`pandas`](https://github.com/pandas-dev/pandas/search?utf8=%E2%9C%93&q=__file__&type=)
* [`numpy`](https://github.com/numpy/numpy/search?utf8=%E2%9C%93&q=__file__&type=)
* [`matplotlib`](https://github.com/matplotlib/matplotlib/search?utf8=%E2%9C%93&q=__file__&type=)

So I think using `__file__` might not be as big of a deal as I suspected. When it comes to storing the files, I think we can use something like [`pgkutil.get_data`](https://docs.python.org/3/library/pkgutil.html#pkgutil.get_data) to load in the files. This would require we include these files in out [`setup.py`](https://setuptools.readthedocs.io/en/latest/setuptools.html#including-data-files).

**Comment by drewejohnson** [comment]
As we move towards files with larger arrays, i.e. xsplot, results, sensitivity, we may have to rethink how we unit test the readers with these large arrays. Currently, we manually type in the whole array, or sections of it [`test_history.py`](https://github.com/CORE-GATECH-GROUP/serpent-tools/commit/78030a8af95649fb470919577064d850c4f5c970#diff-a8f60dc218118b269e439c8f7c245fe6R33).

It has been proposed to use a pickled version of the reader that can be unpickled (loaded into memory) and test against that. However, the unpickling process has the potential to execute arbitrary code and can be a security risk. From [the docs](https://docs.python.org/3/library/pickle.html?#module-pickle)

>  Warning: The pickle module is not secure against erroneous or maliciously constructed data. Never unpickle data received from an untrusted or unauthenticated source. 

So this is not something we want. 

One alternative would be to create compressed versions of the arrays using [`numpy.savez`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez.html) and then load the arrays themselves with [`numpy.load(<file>, pickle=False)`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html). Passing the `pickle=False` argument will not load numpy `object` arrays, meaning there is less risk of malicious code execution.

We can have a script that create these compressed files, and then list the hash/MD5 for the files in release notes, so people can verify the files we present and load.

**Comment by gridley** [comment]
OK, how about this. In general, almost all readers generate a dictionary consisting of named objects. I propose the following.

You could create a dictionary of the contents of each object by using something along this lines of:

`vardict = dict([(xs.name, vars(xs)) for xs in readerResults])`

These can then be printed to a file, gzipped, and compared to the trusted results using diff. This in particular isn't incredibly pythonic but would be compact and secure.

**Comment by drewejohnson** [comment]
That's one method I'm leaning towards. The real issue I want to mitigate is having to write exceptionally large/multidimensional arrays, (a la #13 with upwards of 5 dimensions). 

The numpy savez lets us write a collection of arrays to a file (even [compressed](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez_compressed.html)) which can be loaded in a similar manner to what you describe.
```
 In [1]   import numpy
 In [2]   a1 = numpy.arange(9).reshape((3,3))
 In [3]   numpy.savez('out', a1, a1=a1)
 In [4]   out = numpy.load('out.npz')
 In [5]   out.keys()
 Out[5]  ['a1', 'arr_0']
```

**Comment by gridley** [comment]
Hm, yeah, that would be nice. Have you looked at how efficient compressing these results actually gets? There's not any underlying structure so I'd guess they'd be only about 80% their original size.

**Comment by drewejohnson** [comment]
Closing this as we no longer require the use of `__file__` since we bundle all matlab test files in the package now - #198 and #220 allows us to suppress and test messages from our logging module. Still open for suggestions on improving our testing, but this issue has served its purpose
