### ISSUE TITLE
[support] How to remove INFO messages?

### ISSUE THREAD

**Issue by ondrejch** [CORE-GATECH-GROUP/serpent-tools#104]
## Summary of issue
INFO messages are overwhelming output. Is there a way to suppress them? Thanks.

## Code for reproducing the issue
import serpentTools
bF = 'feedbacks.coe'
bO = serpentTools.read(bF) 
INFO    : serpentTools: Inferred reader for feedbacks.coe: BranchingReader
INFO    : serpentTools: Preparing to read feedbacks.coe
INFO    : serpentTools: Done reading branching file

## Expected outcome
import serpentTools
bF = 'feedbacks.coe'
bO = serpentTools.read(bF) 
(no output)

## Versions
* Version  from ``serpentTools.__version__``
'0.2.2'

* Python version - ``python --version``
Python 3.6.4 (default, Mar 13 2018, 18:16:01)

**Comment by drewejohnson** [comment]
@ondrejch, you can suppress info and debug messages with
```
import serpentTools
from serpentTools.settings import rc
rc.setValue('verbosity', 'warning')
bF = 'feedbacks.coe'
bO = serpentTools.read(bF)
```
