### ISSUE TITLE
[Feature] Chart of nuclides visualization?

### ISSUE THREAD

**Issue by gridley** [CORE-GATECH-GROUP/serpent-tools#108]
Hey folks (probably just Drew),

Do you think adding a visualization tool for DepletedMaterials, with patches in each spot on the cart of the nuclides colored logarithmically or linearly by concentration, would be interesting? May make for some lovely plots comparing spent fuels from various reactors, etc.This shouldn't be incredibly hard to implement if matplotlib patches are used and colored according to a colormap. In particular, getting some time series animations made of the chart of the nuclides would be quite intersting IMO.

**Comment by drewejohnson** [comment]
lol @ the greeting

I like this. I am torn on if it truly fits the scope of the project, or is worth being a secondary feature. On one hand, bundling this capability really bolsters the shine of this project and would very much be a unique contribution. On the other hand, I want to stave off [feature creep](https://en.wikipedia.org/wiki/Feature_creep) for as long as possible, as futile as that may be.

We could add a scripts directory/module that includes some of these nice/on-the-edge features that are part of the repository but are not by default installed with `setup.py` through use of the [`extras`](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) configuration. This way, if some one really just wants basic read and plot capabilities, i.e. for scripting and long-running processes, then they have the option to get just the core functionality.

**Comment by gridley** [comment]
Right, it is indeed a bit outside of the project. It's definitive feature creep. It seems up your alley though considering its relative simplicity to implement in matplotlib, after the data read from Serpent is nicely structured. The "extras" would be great though. I'll probably come back to this in the summer.

BTW, my inspiration is this video, around 18 minutes. https://www.youtube.com/watch?v=md90-FaEw7w

The Copenhagen people don't want to share their code for doing that plotting, so it would be nice to release some open stuff.

**Comment by drewejohnson** [comment]
I'm going to close this for now. If you want to write this up we can consider merging the changes in. I still think such a script would be awesome to make though. We have discussed how to cite/link to projects that use this package in the future. If we get to that point, we will revisit this issue
