### ISSUE TITLE
XSPlot Example not rendering images on RTD

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#123]
## Summary of issue
The images for the XSPlot reader are either not found or failing to load on [readthedocs](http://serpent-tools.readthedocs.io/en/develop/examples/XSPlot.html)

## Code for reproducing the issue
Follow the link

## Expected outcome
Display the images

This could maybe be fixed by moving the plots into the [`docs`](https://github.com/CORE-GATECH-GROUP/serpent-tools/tree/develop/docs/examples/images) folder and changing the links.

**Comment by drewejohnson** [comment]
@gridley Would you be able to take a look at this? I think rtd isn't rendering your example properly

**Comment by gridley** [comment]
Yes, after finals!

Gavin Ridley

**Comment by gridley** [comment]
Yep, I will after my last final on Thursday.

Gavin Ridley

**Comment by drewejohnson** [comment]
Good luck :trophy:

**Comment by drewejohnson** [comment]
In regards to the missing python code blocks, I may have a solution. I think the issue comes from the `.. code:: ipython3 `blocks. The `ipython3` lexer [is finicky depending upon install procedure](https://github.com/jupyter/nbconvert/issues/528) and may not exist on readthedocs.

As for the images, those should be moved to [`docs/examples/images`](https://github.com/CORE-GATECH-GROUP/serpent-tools/tree/develop/docs/examples/images) and all links in the `.rst` file should be changed to point towards the location in that folder. My guess is that sphinx only clones what is inside the `docs` directory, and those images would not exist given the case.

I will add these comments to #125. Once this is fixed and the docs are properly built, we can push out a release with the `xsplot` reader :ok_hand:
