### ISSUE TITLE
[Docs] Unicode characters breaking readthedocs pdf build

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#134]
## Summary of issue
The unicode characters included in our changelog are causing the following errors with our pdf documentation

## Code for reproducing the issue
From the root directory:
```
$ git checkout develop
$ cd docs
$ make clean latexpdf
```

## Actual outcome including console output and error traceback if applicable
```
! Package inputenc Error: Unicode char 🐛 (U+1F41B)
(inputenc)                not set up for use with LaTeX.
```

## Expected outcome
No errors and a non-failing build

## Versions

* Version  from ``serpentTools.__version__``: `0.3.1+5.gc13c3c8`

* Python version - ``python --version`` 3.5.2

* sphinx-build --version -> 1.7.1

## Possible solutions

In increasing difficulty

*. Remove these characters from the changelog/conf.py
*. Do not include the changelog in the pdf manual or include a link that points to the GH link
*. Use a better to make the changelog that renders these characters only for html viewing

**Comment by drewejohnson** [comment]
Paging @DanKotlyar for suggestions

**Comment by DanKotlyar** [comment]
Should we simply delete the characters from conf.py ?

**Comment by drewejohnson** [comment]
That's the most straightforward approach. We lose the nice characters, but it does look a bit more professional. On it!
