### ISSUE TITLE
Unable to import all settings from jupyter

### ISSUE THREAD

**Issue by DanKotlyar** [CORE-GATECH-GROUP/serpent-tools#140]
## Summary of issue
When trying to import settings from the `rc` module, not all of the settings are present. This causes errors when working for more recent readers.

## Code for reproducing the issue
```
from serpentTools.settings import rc
rc['serpentVersion'] = '2.1.30'
```
Furthermore, printing all settings with the `keys` method does not show all settings that
exist in `settings.py`
```
print(rc.keys())

dict_keys(['depletion.metadataKeys', 'depletion.materialVariables', 'depletion.materials', 'depletion.processTotal', 'verbosity', 'serpentVersion', 'xs.variableGroups', 'xs.variableExtras'])
```

## Actual outcome including console output and error traceback if applicable
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-32-0bf10ff8e5ec> in <module>()
      2 import serpentTools
      3 from serpentTools.settings import rc
----> 4 rc['serpentVersion'] = '2.1.30'

~\AppData\Local\Continuum\Miniconda3\lib\site-packages\serpenttools-0.4.0+14.g643554a.dirty-py3.6.egg\serpentTools\settings\__init__.py in __setitem__(self, key, value)
    176     def __setitem__(self, key, value):
    177         self._checkStoreOriginal(key)
--> 178         self.setValue(key, value)
    179 
    180     def __enter__(self):

~\AppData\Local\Continuum\Miniconda3\lib\site-packages\serpenttools-0.4.0+14.g643554a.dirty-py3.6.egg\serpentTools\settings\__init__.py in setValue(self, name, value)
    212         if name not in self:
    213             raise KeyError('Setting {} does not exist'.format(name))
--> 214         self._defaultLoader[name].validate(value)
    215         # if we've made it here, then the value is valid
    216         if self._defaultLoader[name].updater is not None:

~\AppData\Local\Continuum\Miniconda3\lib\site-packages\serpenttools-0.4.0+14.g643554a.dirty-py3.6.egg\serpentTools\settings\__init__.py in validate(self, value)
    102                 raise KeyError('Setting {} is\n{}\nand not one of the allowed '
    103                                'options:\n{}'
--> 104                                .format(self.name, value, opts))
    105         return True
    106 

KeyError: "Setting serpentVersion is\n2.1.30\nand not one of the allowed options:\n['2.1.29']"
```
## Expected outcome
Be able to support this version, and display all settings

## Versions

* Version  from ``serpentTools.__version__`` `0.4.0+15.g1d5480a` off of `results-reader-3` at 1d5480a87c0e6ec25c8d53cf1e5eeb587a001304

* Python version - ``python --version`` Miniconda 3 - python 3.6

* Jupyter 4.4.0
* Jupyter notebook 5.2.2

**Comment by drewejohnson** [comment]
Working with
* jupyter 4.4.0
* jupyter notebook 5.5.2
* python 3.5.2 inside jupyter and when running `setup.py install`

## Attempting to reproduce
Navigating through various versions to attempt to reproduce and find the earliest occurrence of the issue

### Master - serpentTools 0.4.0
Printing settings from inside the branching example yields all settings

### Develop - serpentTools 0.4.0+1.gd96de5b
Printing settings from inside the branching example yields all settings. Same for the depletion example. 

### Issue commit - serpentTools 0.4.0+15.g1d5480a
Branching, depletion, and the troublesome results notebook printed all settings. This worked even with the results notebook in an [untrusted state](https://jupyter-notebook.readthedocs.io/en/stable/security.html#security-in-notebook-documents).

## Requests
Can you comment with the following information:

1. Version of python used to install the package - `python --version` in the same location and manner by which you install
1. Version of python utilized by jupyter by running
```
import sys
print(sys.version)
```
in a cell of the troublesome notebook

My suspicion is that the version of python used to install does not agree with the version of python used to run the notebook. You can see that jupyter is using python 3.6.0 by navigating to the bottom of the file [as found through the raw GitHub viewer](https://raw.githubusercontent.com/CORE-GATECH-GROUP/serpent-tools/1d5480a87c0e6ec25c8d53cf1e5eeb587a001304/examples/ResultsReader.ipynb) or by clicking the `Edit -> Edit Notebook Metadata` option. Why then you're still able to import some of the new features, like the `ResultsReader` it self, but not some settings is very baffling to me

**Comment by DanKotlyar** [comment]
1) The version used to install the package:
Python 3.6.0 
2) After running print(sys.version) in the ResultsReader notebook:
3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]

**Comment by drewejohnson** [comment]
This is very interesting.

Can you reproduce the issue in a plain python file? Either by using `jupyter nbconvert --to=python ResultsReader.ipynb` or by making the following minimal python script:
```
from serpentTools.settings import rc
assert 'depletion.materialVariables' in rc  
# per the issue, this exists
assert 'branching.areUncsPresent` in rc 
# while this doesn't
```
The [`assert statement`](https://docs.python.org/3/reference/simple_stmts.html?highlight=assert#the-assert-statement) can be applied to any key that *should* be present in the loaded settings

**Note** You may have to convert some lines in the converted python file before it will run and not fail outside of where it *should*. Cells that use the `%` magic operators are converted to `get_ipython().run_line_magic(*args)`

**Comment by DanKotlyar** [comment]
When I import serpentTools.settings these are the options that I have:
dict_keys(['depletion.metadataKeys', 'depletion.materialVariables', 'depletion.materials', 'depletion.processTotal', 'verbosity', 'serpentVersion', 'xs.variableGroups', 'xs.variableExtras'])
