### ISSUE TITLE
Feature: XSPlot reader

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#15]
Implement a reader that can be imported from `serpentTools.parsers` that can read xs plot files.

## Format
[SERPENT Wiki](http://serpent.vtt.fi/mediawiki/index.php/Input_syntax_manual#set_xsplot)

**Comment by gridley** [comment]
I think I'll grab this one. Should there be some matplotlib integration?

**Comment by drewejohnson** [comment]
Awesome! I think there definitely should be some matplotlib integration. Ability to plot various cross sections from various nuclides against each other on the same plot would be superb

**Comment by drewejohnson** [comment]
Closed with #95
