### ISSUE TITLE
[ENH] Plotting methods for results reader

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#151]
Implement methods for plotting quantities over time directly on the results reader. This would expedite the process of plotting quantities, such as keff, with something like `reader.plot('keff')` with the ability to plot against burnup in days or MWd/kgU. 

Some of this functionality was displayed when #130 was completed, like [this plot](https://github.com/CORE-GATECH-GROUP/serpent-tools/blob/e4d30fca47790f27449b3edce2022c319b45a8a6/docs/examples/images/ResultsReader_24_1.png), but was not done directly from the reader.

## Desired options
1. Control over confidence interval for uncertainties
1. Plot multiple quantities on the same plot with appropriate labels, e.g. `plot(['impKeff', 'anaKeff'])`

## See Also
1. [Plotting section of developer guide](http://serpent-tools.readthedocs.io/en/latest/develop/plots.html)
1. [Depletion plot routines](http://serpent-tools.readthedocs.io/en/latest/examples/DepletionReader.html#data-retrieval)

**Comment by DanKotlyar** [comment]
I will complete this assignment.
