### ISSUE TITLE
[BUG] reshape scattering matrix

### ISSUE THREAD

**Issue by DanKotlyar** [CORE-GATECH-GROUP/serpent-tools#158]
## Summary of issue
The reshape functionality fails simply because the variable ng can be float rather than an int.
## Code for reproducing the issue
In the containers under the method _cleanData:
ng = self.numGroups
....
...
             else:
                value = value.reshape(ng, ng)
        return value

Reshape function accepts only integers, however ng might be float (e.g. 24.0)
## Actual outcome including console output and error traceback if applicable
I suggest to modify the line to:
ng = int(self.numGroups)
or:
value = value.reshape(int(ng), int(ng))
## Expected outcome
Reshape should be successful. 
## Versions

* Version  from ``serpentTools.__version__``

* Python version - ``python --version``

* IPython or Jupyter version if applicable

**Comment by drewejohnson** [comment]
This is a duplicate issue of #152. The proposed solution is pull request #154
