### ISSUE TITLE
[API] Importable reference files

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#179]
This enhancement would allow the user, our test suite, and our examples, to import *paths* to our reference files. Currently, all of our files are in one of two locations: `serpentTools/tests` or `examples`. The real hassle here is that, if someone wants to walk through our examples, they have to be in the same directory as the examples directory. If we move to a non-git-based installation procedure, such as `pip`, then the examples will be difficult to walk through because:

1. The user might not know the exact directory of the test files, and, more importantly,
1. We are currently not set up to move these data files with the `setup.py` script.

The `setup.py` script moves all python files in the packages that you request
https://github.com/CORE-GATECH-GROUP/serpent-tools/blob/b2749b2acd6e09506604c8b556bbb7ee89fe1507/setup.py#L47 and non-python files through the `data_files` parameter 
https://github.com/CORE-GATECH-GROUP/serpent-tools/blob/b2749b2acd6e09506604c8b556bbb7ee89fe1507/setup.py#L61

Therefore, non of the matlab files we use for testing are installed during the install procedure.

## Proposal

I propose we create a new directory `serpentTools/data`, from which one can import paths to all our files. We could do this via

- Module attributes, i.e. `serpentTools.data.REF_DEP`
- Dictionary of paths: `serpentTools.data.paths = {'ref_dep': <path/to/depletion>, ...}`
- or both.

The benefit of this approach is that, from anywhere in the system, so long as the user has run our `setup.py`, they can run any of our examples by importing these paths.

The benefit of using paths is that we don't have to change the internal structure of our readers to work off of strings or file stream objects.

This would require minor tweaks to the test files and to the examples as well.

**Comment by drewejohnson** [comment]
Been giving this some thought, and I think this has a lot of merit. I would like to move the files over to [`git lfs`](https://git-lfs.github.com/) since these file objects are largely static and, while our test structure may change in the future, the output files will *likely* not change too much. Moving to `git lfs` also allows us to track larger files in the repository while making the cloning process and diff process shorter. Diffing files tracked with `gif lfs` is not trivial, however.

## Pros
- All of our files are contained in one simple repository
- Less extra work to track down files
- `git lfs` can be used to reduce the size of stuff tracked via `git` and expedite cloning/diffing process

## Cons
- Each individual input file will have to be bundled in `setup.py`
  - Could be simplified if `setuptools` supports globbed file paths, i.e. `data/*.m`
- Harder / impossible to obtain *just* the python part of the package, as all the matlab files are included

I'm going to include @DanKotlyar and @gridley in this because extra opinions are great. If we do move these files around, I would like to offer you the opportunity to move the files over to keep a balanced contribution history, and not make it look like some of your contributions have been purged from the repository. If you're fine with me moving these over and modifying the tests, solely the reading aspects, please let me know in the comments below.

## Proposed path forward
1. Create `serpentTools/data` directory
1. Move files over into this directory 
1. Setup framework for importing file paths, something like:
```
from serpentTools.data import PATHS, getReader

ref_dep = PATHS['ref_dep.m']
# or, without interacting with the file path directly
ref_dep = getReader('ref_dep.m')
```
1. Update the part of our unittests and examples where reference files are loaded
1. Bundle files into `setup.py` to be included in installation

**Comment by gridley** [comment]
Well, I don't mind at all. If you don't use `lfs`, you could just symlink stuff in a new directory rather than actually moving stuff. Then the unified imports should work with minimal change required.

**Comment by drewejohnson** [comment]
Symlinking is a good option as well, thanks for suggesting that. I'll mull some stuff over and then have a PR put forward probably next week on this topic.
