### ISSUE TITLE
Detectors with time binning 

### ISSUE THREAD

**Issue by vvaltavi** [CORE-GATECH-GROUP/serpent-tools#312]
## Summary of issue

Detectors with [time binning](http://serpent.vtt.fi/mediawiki/index.php/Input_syntax_manual#det_di) have 13 columns in the detector output file (an additional column indicating the time bin between the normal 1st and 2nd column) and thus get mixed up with the Serpent 1 style detector output with the number of scores as the 13th column.

The Detector Reader reads the tally values from column 11 and error values from column 12 as usual. The problem is that in detectors with time binning, the tally values are actually at column 12 and error values at column 13.  

I'm not sure what's the best approach for this at serpentTools side, but the best way to figure out whether the detector that has 13 columns has time binning is to check for the

`DET<name>T`

array that is printed in the detector file and gives the time binning associated with the detector.

## Code for reproducing the issue

Serpent input:

    set title "Homogeneous case"

    % --- Disable group constant calculation

    set gcu -1

    % --- Geometry is just a cube

    surf 2 cuboid -100.0 100.0 -100.0 100.0 -100.0 100.0

    % --- Cell definitions:

    cell  3  0  fuel     -2
    cell 99  0  outside   2     % Outside world

    % --- Fuel material:

    mat fuel   sum vol 8.0000E+06
    8016.03c  0.316667
    1001.03c  0.633333
    92235.03c 0.0015
    92238.03c 0.0485
    5010.03c  0.000115797

    % --- Reflective boundary conditions:

    set bc 2 2 2

    % --- Neutron population:

    set pop 1000 10 10

    % --- Normalization

    set power 1.0

    % --- Specify a time binnig (10 bins between 0 and 50 microseconds)

    tme dettime 2 10 0 50e-6

    % --- Detector with time binning

    det FP dr -8 void di dettime

Produced input_det0.m:

    DETFP = [
        1    1    1    1    1    1    1    1    1    1    1  8.68766E-01 0.00612 
        2    2    1    1    1    1    1    1    1    1    1  1.14554E-01 0.03156 
        3    3    1    1    1    1    1    1    1    1    1  1.49875E-02 0.10890 
        4    4    1    1    1    1    1    1    1    1    1  1.51392E-03 0.28029 
        5    5    1    1    1    1    1    1    1    1    1  1.60274E-04 1.00000 
        6    6    1    1    1    1    1    1    1    1    1  1.89739E-05 1.00000 
        7    7    1    1    1    1    1    1    1    1    1  0.00000E+00 0.00000 
        8    8    1    1    1    1    1    1    1    1    1  0.00000E+00 0.00000 
        9    9    1    1    1    1    1    1    1    1    1  0.00000E+00 0.00000 
       10   10    1    1    1    1    1    1    1    1    1  0.00000E+00 0.00000 
    ];

    DETFPT = [
     0.00000E+00  5.00000E-06  2.50000E-06
     5.00000E-06  1.00000E-05  7.50000E-06
     1.00000E-05  1.50000E-05  1.25000E-05
     1.50000E-05  2.00000E-05  1.75000E-05
     2.00000E-05  2.50000E-05  2.25000E-05
     2.50000E-05  3.00000E-05  2.75000E-05
     3.00000E-05  3.50000E-05  3.25000E-05
     3.50000E-05  4.00000E-05  3.75000E-05
     4.00000E-05  4.50000E-05  4.25000E-05
     4.50000E-05  5.00000E-05  4.75000E-05
    ];

Postprocessing with serpentTools:

    #!/usr/bin/env python
    # -*- coding: utf-8 -*-

    import serpentTools as sT

    dr = sT.DetectorReader("./input_det0.m")
    dr.read()

    det = dr.detectors["FP"]

    print(det.tallies)
    print(det.errors)

## Actual outcome including console output and error traceback if applicable

    [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
    [8.68766e-01 1.14554e-01 1.49875e-02 1.51392e-03 1.60274e-04 1.89739e-05
     0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]

## Expected outcome
    [8.68766e-01 1.14554e-01 1.49875e-02 1.51392e-03 1.60274e-04 1.89739e-05
     0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00]
    [0.00612 0.03156 0.1089  0.28029 1.      1.      0.      0.      0.
     0.     ]

## Versions

- Serpent 2.1.31
- serpentTools 0.7.0+17.g7ae29a3.dirty
- Python 3.6.7

**Comment by drewejohnson** [comment]
Interesting. I've never worked with a time-binned detector, but I think we can make a fix. Since we don't support serpent1, we can assume that detectors do not have the scores column anymore. Then, if a bins array is passed with a 13th column, we know this means time. A less elegant way would be to assume that, regardless of array structure, the tallies are always in the second to last column with errors in the last. 

Thanks for pointing this out. I'll look into a solution
