### ISSUE TITLE
BUG Failure to read files with burnup and no universes

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#322]
## Summary of issue
If there are no universes in the file, then the result counter does not get incremented due to an unreachable line

https://github.com/CORE-GATECH-GROUP/serpent-tools/blob/b3f3c39609319985f7047dd6fed52654e285cd0b/serpentTools/parsers/results.py#L186-L190

This causes the `_postread` method to fail, thinking the file is incomplete when it actually isn't. This should have been fixed with #231 and the inclusion of the settings `results.expectGcu`.

## Code for reproducing the issue
Read the [now deleted](https://github.com/CORE-GATECH-GROUP/serpent-tools/pull/231/commits/264901eb1157f8dd672fef9c873312425300792a)  [result file without universes](https://github.com/CORE-GATECH-GROUP/serpent-tools/blob/f106d735fb31fc6a8a04d5904f69d1bd45b21e1c/serpentTools/data/pwr_noUniv_res.m)

## Actual outcome including console output and error traceback if applicable
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    r = serpentTools.read("leqi_res.m", "results")
  File "/home/drew/.local/lib/python3.7/site-packages/serpentTools-0.7.0+26.gb3f3c39-py3.7.egg/serpentTools/parsers/__init__.py", line 155, in read
    returnedFromLoader.read()
  File "/home/drew/.local/lib/python3.7/site-packages/serpentTools-0.7.0+26.gb3f3c39-py3.7.egg/serpentTools/parsers/base.py", line 54, in read
    self._postcheck()
  File "/home/drew/.local/lib/python3.7/site-packages/serpentTools-0.7.0+26.gb3f3c39-py3.7.egg/serpentTools/parsers/results.py", line 390, in _postcheck
    self._inspectData()
  File "/home/drew/.local/lib/python3.7/site-packages/serpentTools-0.7.0+26.gb3f3c39-py3.7.egg/serpentTools/parsers/results.py", line 375, in _inspectData
    self._counter['rslt'], self._counter['meta']))
serpentTools.messages.SerpentToolsException: The file leqi_res.m is not complete. The reader found 0 universes, 0 time-points, and 2 overall result points 
```
## Expected outcome
Reader can read the file without universes, preferably without the need to set `results.expectGcu`

## Versions

* Version  from ``serpentTools.__version__`` develop version b3f3c39

* Python version - ``python --version`` `3.7`

**Comment by atom-kj** [comment]
I encountered the same error even though 'results.expectGcu' is set 'false'
I used 'set gcu -1' 'set cmm 0', and 'set repro 0'

serpentTools version : 0.7.0+34.g7d9899c 
Python version : 3.7.2
Serpent version : 2.1.29

**Comment by drewejohnson** [comment]
@atom-kj thank you for your feedback. The setting `results.expectGcu` has been removed, as it is no longer needed. The `ResultsReader` should be capable of parsing files without group constant data now. If you experience further issues, please raise them here or in a separate issue and I will work to resolve them. Thanks!
