### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by ondrejch** [CORE-GATECH-GROUP/serpent-tools#443]
## Summary of issue
Fails to install on Ubuntu 21.04

## Code for reproducing the issue
python3 -m pip install --user --upgrade pip https://github.com/CORE-GATECH-GROUP/serpent-tools/releases/download/0.9.3/serpentTools-0.9.3-py3-none-any.whl

## Actual outcome including console output and error traceback if applicable
ERROR: Package 'serpenttools' requires a different Python: 3.9.4 not in '<3.9,>=3.5'

## Expected outcome

Correct installation

## Versions

Python 3.9.4

Please provide the following:

* Version  from ``serpentTools.__version__``
* Python version - ``python --version``
* IPython or Jupyter version if applicable
* If using the development version, the output from ``git describe``

**Comment by ondrejch** [comment]
BTW I checked out the repo version (0.10.0.dev0) and it appears to work fine with Python 3.9.4,

**Comment by drewejohnson** [comment]
Thanks for bringing this up! I think that upper limit was added out of an abundance of caution. Looking through some of the changelog, and my own experience, I think we can easily support 3.9. I'll add it to the next release

For the record, I've had good success with conda environments where the python is at a different version than the one shipped by my distribution (3.7 vs. 3.9). If you need it to be pip-installable, that's probably the way to go
