### ISSUE TITLE
BUG Py 3.9 github action not working

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#466]
## Summary of issue
See #465 test summary information. Py 3.9 hanging

## Versions

Please provide the following:

* Version  from ``serpentTools.__version__``
* Python version - ``python --version``
* IPython or Jupyter version if applicable
* If using the development version, the output from ``git describe``

**Comment by drewejohnson** [comment]
py3.9 testing is not on `develop` branch. The confusion between `develop` and `master` is too confusing and should be cleaned up. 

@DanKotlyar I think this project is in need of some repository structure updates. What do you think about the following changes

- new branch `main` that is in line with `master`
- change default branch from `develop` to `main`

`develop` and `master` have diverged a lot. But, changes that have fixed various bugs are in `master` and have been / should be release

**Comment by DanKotlyar** [comment]
@drewejohnson I am ok with these changes.

**Comment by drewejohnson** [comment]
@DanKotlyar ping on needing actions from you in order to make these changes

**Comment by drewejohnson** [comment]
@DanKotlyar I'm thinking about doing some serpent-tools updates over the next month or so. Having the changes from https://github.com/CORE-GATECH-GROUP/serpent-tools/issues/466#issuecomment-1279286356 incorporated would make development and deployment much easier. If you need anything from me please let me know. But I don't seem to have the permissions to make the changes on my own

**Comment by drewejohnson** [comment]
I don't think that's necessary just for this change. Here are the GitHub docs on changing the default branch for a repository - https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

**Comment by DanKotlyar** [comment]
I just changed the default branch to ``main``. Any other changes I need to apply?

**Comment by drewejohnson** [comment]
That seems to have done the trick. Thanks @DanKotlyar!

**Comment by drewejohnson** [comment]
Working now as of https://github.com/CORE-GATECH-GROUP/serpent-tools/actions/runs/5220365753/job/14131376512
