### ISSUE TITLE
ENH Support installing with conda

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#494]
**Is your feature request related to a problem? Please describe.**
Many users are using `conda` as their package manager to install e.g., numpy, scipy, pandas, etc. We should support this, such that users can install with `conda install -c conda-forge serpentTools` (maybe with a different channel?)

**Describe alternatives you've considered**
`pip install` is fine, but then you often need to be managing two package managers: pip and conda, which is not always fun.

**Additional context**

Some (hopefully) useful links
- https://conda-forge.org/
- https://github.com/conda-forge/staged-recipes
- https://github.com/idaholab/moose/tree/next/conda
- https://github.com/conda-forge/openmc-feedstock

**Comment by drewejohnson** [comment]
@DanKotlyar I think we should provide this functionality, and I'm happy to be a maintainer for it - https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role

Do you think this is worthwhile? And would you and/or someone in the lab be open to being co-maintainers of the conda recipe with me?

**Comment by DanKotlyar** [comment]
Hi Drew,
I will read through it and reply a bit later.
Thanks,
Dan

**Comment by drewejohnson** [comment]
@DanKotlyar I'm still interested in moving forward on this and acting as a maintainer. Have you given it any thought?

**Comment by DanKotlyar** [comment]
@drewejohnson Should I change your role to have the ability to maintain the code?

**Comment by DanKotlyar** [comment]
@drewejohnson I just added you as the maintainer.

**Comment by drewejohnson** [comment]
Staged recipe is up - https://github.com/conda-forge/staged-recipes/pull/25751

**Comment by DanKotlyar** [comment]
Thanks!
