### ISSUE TITLE
Reading User Defined Variables from .coe files with BranchingReader [Feature]

### ISSUE THREAD

**Issue by mlouis9** [CORE-GATECH-GROUP/serpent-tools#509]
User defined variables in Serpent can make post-processing of cross sections much easier by explicitly specifying historical parameters and branch parameters (For more information on branch variables, see the "var" subcard of the "branch" definition in the Serpent Wiki). Currently, the branching reader does not support reading these user defined variables (which are printed directly to the .coe file).

**Request**
- Update the BranchingReader to allow reading these user defined variables
- Add a new attribute to the HomogUniv container (e.g. "userDefined") to store these user defined variables for each branch.

An example of an output (.coe) file containing user defined variables specifying the historical depletion conditions (historical fuel temperature, boron concentration, and moderator temperature) is given below:

1 288 1 18 2
4 nom nom nom nom
6 VERSION 2.1.32 DATE 23/08/31 TIME 10:18:19 **HTFU 900 HTM 580 HBC 750**
0.5 1 16
0 181
INF_FLX 2  2.45368E+17  1.41838E+16
INF_KINF 1  5.50705E-01
INF_REP_TIME 0
INF_PROMPT_LIFE 0
INF_TOT 2  5.50594E-01  1.36464E+00
...

**Comment by drewejohnson** [comment]
Thanks for the feature request @mlouis9!

This is something we kind of do already, but maybe not quite what you're looking for. The state data are stored on the `BranchContainer`  objects attached to the `BranchingReader`. Paraphrasing from our [documentation](https://serpent-tools.readthedocs.io/en/master/examples/Branching.html#user-control)

```python
>>> r1 = serpentTools.readDataFile(branchFile)
>>> b1 = r1.branches['B1000', 'FT600']
>>> b1.stateData
{'BOR': 1000.0,
 'DATE': '17/12/19',
 'TFU': 600,
 'TIME': '09:48:54',
 'VERSION': '2.1.29'}
```
And since the `HomogUniv` objects are retrievable from these `BranchContainer` instances, the user parameters / state data are close by, just not directly on the `HomogUniv` object. This isn't  exactly what you're looking for, but would it be able to help you accomplish what you need? Maybe with some minor adjustments to processing scripts?

**Comment by mlouis9** [comment]
Yeah, I was aware that you could access that data in the "stateData"
attribute, but it's kind of inconvenient that these variables are treated
differently than any other variable in the .coe file: which is where the
post-processing difficulties come into play. For instance, xs-interface
(one of CORE's other projects that you've probably heard of) stores a
complicated dictionary including only the homogenized universes for each
branch and universe, so the end-user only has access to variables readable
in the homogUniverse containers.

Of course this is something that could also be changed on the xs-interface
side of things (wold have to manually
.addData(branch.stateData['user_variables']) to the homogUniverses), but it
felt more appropriate (to me) to include the user defined variables along
with all of the other variables in the homogenized universe containers, so
you could do something like:

coe = serpentTools.read(coe_fname)
nom_state = coe.get(('nom', 'nom', 'nom', 'nom'))
homUniv = nom_state.getUniv('0', burnup=0.5)
print(homUniv['HTFU'])

which makes it much easier to tie state + history variations with every
cross section set (associated with a burunup point + universe).  But
perhaps this isn't really appropriate, because the same variable would be
included across all burnup steps and all universes (which is kind of
redundant), and this variable (unlike all others in the homogUniv
container) doesn't follow the group structure, but is just a lone value.

Let me know what you think, but if it comes down to it I guess the changes
are more appropriate for xs-interface in scope anyways, since serpentTools
is meant to be a more general tool.

-Matthew

**Comment by mlouis9** [comment]
After playing around with implementing this, I've found that it conflicts with some of the functionality in xs.py, and I've figured out an easier way to implement the desired feature in xs-interface, and so I'm going to close this issue.
