### ISSUE TITLE
BUG numpy 2.0 removed longfloat

### ISSUE THREAD

**Issue by maratm123** [CORE-GATECH-GROUP/serpent-tools#515]
## Summary of issue

Hi Drew, I was trying to runs SeprentTools and got the following msg.  
Any idea what am i doing wrong?
Marat

## Actual outcome including console output and error traceback if applicable

Traceback (most recent call last):
  File "/home/maratm/MSR/MUSTAFA/run_msr.py", line 5, in <module>
    import serpentTools
  File "/home/maratm/.local/lib/python3.10/site-packages/serpentTools/__init__.py", line 10, in <module>
    from serpentTools.detectors import *
  File "/home/maratm/.local/lib/python3.10/site-packages/serpentTools/detectors.py", line 28, in <module>
    from numpy import (
  File "/usr/local/lib/python3.10/dist-packages/numpy-2.0.0rc2-py3.10-linux-x86_64.egg/numpy/__init__.py", line 123, in <module>
    from ._core import (
ImportError: cannot import name 'longfloat' from 'numpy._core' (/usr/local/lib/python3.10/dist-packages/numpy-2.0.0rc2-py3.10-linux-x86_64.egg/numpy/_core/__init__.py)

## Versions

Please provide the following:

* Version  from ``serpentTools.__version__10.1``
* Python version - ``python --version 3.10``
* IPython or Jupyter version if applicable
* If using the development version, the output from ``git describe``

**Comment by drewejohnson** [comment]
Hi @maratm123, sorry to hear you're having this problem. I think it might be related to numpy 2.0, which released recently. Are you able to import numpy into a python environment? e.g.,
```python
import numpy
```

If you're able to do that, we might get useful information about the bug.

**Comment by drewejohnson** [comment]
Looking a bit more, you're on a pre-release of numpy

> "/usr/local/lib/python3.10/dist-packages/numpy-2.0.0rc2-py3.10-linux-x86_64.egg/numpy/init.py",

so maybe downgrading numpy will help

**Comment by maratm123** [comment]
Thanks, Drew. Any particular version of numpy?

**Comment by drewejohnson** [comment]
> Thanks, Drew. Any particular version of numpy?

Anything less than 2.0. The latest release is 1.26 so try that?

**Comment by drewejohnson** [comment]
We got bit by this in testing - https://github.com/CORE-GATECH-GROUP/serpent-tools/actions/runs/9555941645/job/26340216490?pr=519#step:5:21

Looks like `numpy 2.0` removed `longfloat` in favor of `longdouble`
