### ISSUE TITLE
[ENH] Results file reader

### ISSUE THREAD

**Issue by drewejohnson** [CORE-GATECH-GROUP/serpent-tools#7]
Implement a reader that can be imported from `serpentTools.parsers` that reads data from the results file.

## Format 
[SERPENT Wiki](http://serpent.vtt.fi/mediawiki/index.php/Output_parameters)

Data is presented in three tiers:
1. File wide parameters such as version, run time, and parallelization metrics
1. For each burnup point:
    1. Cycle data, like criticality eigenvalues
    1. For each universe listed with `set gcu`:
        1. Micro and macro energy group boundaries [intermediate group structure and broad group]
        1. Micro and macro group fluxes
        1. Homogenized parameters, like infinite medium and critical leakage cross sections [if requested], and kinetic parameters

## Requirements
1. Store requested cross sections and other parameters for each universe at each burnup state
1. Easy extraction of these data

## Optional
1. Rudimentary plotting of quantities over time, like criticality eigenvalues
1. Output the data with some template engine like [Jinja2](http://jinja.pocoo.org/) or [Mako](http://www.makotemplates.org/)

## Prerequisites
- [x] #11

**Comment by gridley** [comment]
Is anyone working on this? I was going to start using your tools today to parse some _res.m files, but sadly couldn't. If I made a PR this time, it would be up-to-specs. :D

**Comment by drewejohnson** [comment]
That's definitely something we want to finish up. @CORE-GATECH is working on it as we speak. Nothing has been pushed yet

**Comment by drewejohnson** [comment]
Closed with #130
